version: 2.1

orbs:
   node: circleci/node@1.1.6

jobs:
  build_and_run:
    docker:
      - image: cypress/browsers:<chrome>
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Run the app
          command: npx cypress run
    working_directory: ~/Cypress_AMPOL_UI
      
workflows:
  run_my_app:
    jobs:
      - build_and_run
