version: 2.1
jobs:
  build_and_run:
    docker:
      - image: circleci/node:
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save        
      - run:
          name: Run the app
          command: |
            npx cypress run
workflows:
  run_my_app:
    jobs:
      - build_and_run
